### PR TITLE
Update main-content.html

### PR DESCRIPTION
**Pull request by shibam17**
Made the description shorter and simpler.

### CODE REVIEW

**Comment by libremente** [comment]
Hi @soulhunter10737 and thanks for your time.
Could you please:
* indicate the issue you are trying to solve in the comment section of the PR;
* review the Italian used in the text? Right now it's quite hard to read.

Thanks for your contribution

**Comment by soulhunter10737** [comment]
@libremente it was regarding issue #124 I enhanced the texts and made it simpler keeping only the important points.

**Comment by ioggstream** [comment]
@soulhunter10737 

>All the Italian texts are correct

Sadly there are various mistakes, but you are welcome to fix them :)

**Comment by soulhunter10737** [comment]
can you explain please 👍

**Comment by bfabio** [comment]
@shibam17 we closed this with #153, thanks for your time!

**Pull request closed without merging**
